# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20171029_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_points',
            field=models.IntegerField(default=0),
        ),
    ]
