# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20171029_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=200)),
                ('away_team', models.CharField(max_length=200)),
                ('alg1_goals', models.IntegerField(default=0)),
                ('alg2_goals', models.IntegerField(default=0)),
                ('alg3_goals', models.IntegerField(default=0)),
                ('alg4_goals', models.IntegerField(default=0)),
                ('alg5_goals', models.IntegerField(default=0)),
                ('alg6_goals', models.IntegerField(default=0)),
                ('alg7_goals', models.IntegerField(default=0)),
                ('alg8_goals', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
